name: "Pull Min.io Asset Action"
description: "Pull Assets from Min.io and Push to S3."
inputs:
  aws-account-id:
    description: "ARN of the AWS IAM role to assume"
    required: true

  aws-region:
    description: "AWS Resource Region"
    required: true

  min-io-uri:
    description: "Min.io Resource URI"
    required: true

  min-io-access-key-id:
    description: "Min.io Resource Access Id"
    required: true

  min-io-access-secret-key:
    description: "Min.io Resource secret key"
    required: true

  min-io-folder:
    description: "Min.io Resource folder location"
    required: true

  min-io-asset-name:
    description: "Min.io Resource file name"
    required: true

  s3-bucket-location:
    description: "The S3 bucket location to push the data asset to"
    required: true

  file-extension:
    description: "The file extension type, e.g. gz, csv etc etc"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github
    - run: aws sts get-caller-identity
      shell: bash
      

    - name: Pull Data and Push Data from Min.io to s3
      run: |
        wget https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        sudo mv mc /usr/bin
        mc --help
        mc alias set mycloud/ ${{ inputs.min-io-uri }} ${{ inputs.min-io-access-key-id }} ${{ inputs.min-io-access-secret-key }} --api S3v4
        mc ls mycloud/${{ inputs.min-io-folder }}/
        mc cp mycloud/${{ inputs.min-io-folder }}/${{ inputs.min-io-asset-name }}.csv .
        mv ./${{ inputs.min-io-asset-name }}.csv ${{ inputs.min-io-asset-name }}-$(date +%d-%m-%Y).${{ inputs.file-extension }}
        aws s3 ls
        aws s3 cp ./${{ inputs.min-io-asset-name }}-$(date +%d-%m-%Y).csv ${{ inputs.s3-bucket-location }}
      shell: bash
    