name: "Pull Min.io Asset Action"
description: "Pull Assets from Min.io and Push to S3."
inputs:
  aws-account-id:
    description: "ARN of the AWS IAM role to assume"
    required: true

  aws-region:
    description: "AWS Resource Region"
    required: true

  min-io-uri:
    description: "Min.io Resource URI"
    required: true

  min-io-access-key-id:
    description: "Min.io Resource Access Id"
    required: true
    # default: "s3_seetransparent_awaze_rw"

  min-io-access-secret-key:
    description: "Min.io Resource secret key"
    required: true
    # default: "9z7AldBwC07T"

  min-io-folder:
    description: "Min.io Resource folder location"
    required: true
    # default: "seetransparent-awaze"

  min-io-asset-name:
    description: "Min.io Resource file name"
    required: true
    # default: "Supply_sample.csv"

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github
    - run: aws sts get-caller-identity
      shell: bash

    - name: Pull Data and Push Data from Min.io to s3
      run: |
        wget https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        sudo mv mc /usr/bin
        mc --help
        mc alias set mycloud/ ${{ inputs.min-io-uri }} ${{ inputs.min-io-access-key-id }} ${{ inputs.min-io-access-secret-key }} --api S3v4
        mc ls mycloud/${{ inputs.min-io-folder }}/
        mc cp mycloud/${{ inputs.min-io-folder }}/${{ inputs.min-io-asset-name }}.csv .
        mv ./${{ inputs.min-io-asset-name }}.csv ${{ inputs.min-io-asset-name }}-$(date +%d-%m-%Y).csv
        aws s3 ls
        aws s3 cp ./${{ inputs.min-io-asset-name }}-$(date +%d-%m-%Y).csv s3://vrukl-bi-qb-dev-ingestion/snowflake/Lake/Transparent/Regular_Feeds/
      shell: bash
    